import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
const API='/api';
function App(){const[songs,setSongs]=useState([]),[q,setQ]=useState(''),[current,setCurrent]=useState(null),[admin,setAdmin]=useState(false),[login,setLogin]=useState(false),[token,setToken]=useState(localStorage.kt_token||'');
const load=async()=>{const r=await fetch(API+'/songs?q='+encodeURIComponent(q));setSongs(await r.json())};useEffect(()=>{load()},[q]);
return <><header><div className="logo">♛ <span>آهنگ های تتلو<br/><small>۲۰۲۶__۱۴۰۵</small></span></div><nav><a>خانه</a><a href="#songs">آهنگ‌ها</a><button onClick={()=>token?setAdmin(true):setLogin(true)}>{token?'مدیریت':'ورود مدیریت'}</button></nav></header>
<main><section className="hero"><div><b className="tag">MUSIC • 2026</b><h1>آهنگ های تتلو<br/><i>۲۰۲۶__۱۴۰۵</i></h1><p>آرشیو موسیقی با طراحی مدرن، جستجوی سریع و پخش آنلاین.</p><a className="cta" href="#songs">مشاهده آهنگ‌ها ↓</a></div><div className="disc">KT</div></section>
<section id="songs" className="library"><div className="head"><div><b className="tag">LIBRARY</b><h2>جدیدترین آهنگ‌ها</h2></div><input placeholder="جستجوی آهنگ..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="list">{songs.map((s,i)=><article className="song" key={s.id}><button className="num" onClick={()=>setCurrent(s)}>▶</button><div><b>{s.title}</b><span>{s.artist} • {s.genre||'موسیقی'} {s.year&&'• '+s.year}</span></div><em>{s.duration}</em><button className="play" onClick={()=>setCurrent(s)}>پخش</button></article>)}</div>{!songs.length&&<div className="empty">هنوز آهنگی اضافه نشده؛ از پنل مدیریت اولین آهنگ را اضافه کن.</div>}</section></main>
{current&&<Player song={current} close={()=>setCurrent(null)}/>}
{login&&<Login close={()=>setLogin(false)} ok={t=>{setToken(t);localStorage.kt_token=t;setLogin(false);setAdmin(true)}}/>}
{admin&&<Admin token={token} songs={songs} refresh={load} close={()=>setAdmin(false)} logout={()=>{localStorage.removeItem('kt_token');setToken('');setAdmin(false)}}/>}
</>}
function Player({song,close}){const[play,setPlay]=useState(false);return <div className="player"><div><b>{song.title}</b><span>{song.artist}</span></div>{song.audio?<audio src={'/uploads/'+song.audio} controls autoPlay/>:<button className="cta" onClick={()=>setPlay(!play)}>{play?'توقف':'پخش'}</button>}<button onClick={close}>×</button></div>}
function Login({close,ok}){const[u,setU]=useState('admin'),[p,setP]=useState(''),[e,setE]=useState('');return <div className="modal"><form onSubmit={async x=>{x.preventDefault();const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p})});const d=await r.json();r.ok?ok(d.token):setE(d.error)}}><button type="button" className="x" onClick={close}>×</button><b className="tag">SECURE ADMIN</b><h2>ورود مدیریت</h2><input value={u} onChange={e=>setU(e.target.value)} placeholder="نام کاربری"/><input type="password" value={p} onChange={e=>setP(e.target.value)} placeholder="رمز عبور"/>{e&&<small className="err">{e}</small>}<button className="cta">ورود</button></form></div>}
function Admin({token,songs,refresh,close,logout}){const[form,setForm]=useState({title:'',artist:'تتلو',genre:'',year:'2026',duration:'',description:''}),[audio,setAudio]=useState(null),[cover,setCover]=useState(null),[msg,setMsg]=useState('');
const add=async e=>{e.preventDefault();const f=new FormData();Object.entries(form).forEach(([k,v])=>f.append(k,v));if(audio)f.append('audio',audio);if(cover)f.append('cover',cover);const r=await fetch(API+'/songs',{method:'POST',headers:{Authorization:'Bearer '+token},body:f});setMsg(r.ok?'آهنگ اضافه شد':'خطا در ذخیره');if(r.ok){setForm({title:'',artist:'تتلو',genre:'',year:'2026',duration:'',description:''});setAudio(null);setCover(null);refresh()}};return <div className="adminModal"><div className="adminPanel"><div className="adminTop"><div><b className="tag">CONTROL CENTER</b><h2>پنل مدیریت</h2></div><button onClick={close}>×</button></div><div className="stats"><div><span>آهنگ‌ها</span><b>{songs.length}</b></div><div><span>امنیت</span><b>فعال</b></div><div><span>مدیریت</span><b>Admin</b></div></div><form onSubmit={add} className="form"><input required placeholder="عنوان آهنگ" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input placeholder="نام هنرمند" value={form.artist} onChange={e=>setForm({...form,artist:e.target.value})}/><input placeholder="سبک" value={form.genre} onChange={e=>setForm({...form,genre:e.target.value})}/><input placeholder="سال" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/><input placeholder="مدت" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/><textarea placeholder="توضیحات" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><label>فایل صوتی <input type="file" accept="audio/*" onChange={e=>setAudio(e.target.files[0])}/></label><label>کاور <input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setCover(e.target.files[0])}/></label><button className="cta">افزودن آهنگ</button>{msg&&<small>{msg}</small>}</form><button className="logout" onClick={logout}>خروج از مدیریت</button></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
